### PR TITLE
Add support for key wrap as a cipher mode

### PR DESCRIPTION
**Pull request by jack-fortanix**
Change to vendor submitted upstream in PR https://github.com/ARMmbed/mbedtls/pull/2463

### CODE REVIEW

**Comment by jack-fortanix** [comment]
PR has been merged upstream now but still waiting for a new release which probably isn't going to happen soon since given 2.17 was just pushed.

**Comment by jack-fortanix** [comment]
This can be merged after #43

**Comment by Goirad** [comment]
So this is ready to merge now?

**Pull request merged**
