### PR TITLE
Mpi is Sync

### PR DESCRIPTION
**Pull request by jethrogb**

### CODE REVIEW

**Comment by zugzwang** [comment]
The failed build is odd

**Comment by Taowyoo** [comment]
Close this old PR because of change of default branch to `main`.
See more:
- https://github.com/fortanix/rust-mbedtls/issues/320

Please reopen this if have further problems or you think this PR need to be rebased onto `main` (this is needed on `mbedtls 2.28.X`)

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
I am wondering if this PR still valid?
CC: @jethrogb @zugzwang

**Pull request closed without merging**
