### PR TITLE
[back-port][v0.9] fix: return error when verify empty cert chain

### PR DESCRIPTION
**Pull request by Taowyoo**
back-port #308 to 0.9.X

### CODE REVIEW

**Comment by Taowyoo** [comment]
bors try

**Comment by raoulstrackx** [comment]
CI failed with:
```
  thread 'main' panicked at '"x509_san_other_name_union_(unnamed_at_vendor/include/mbedtls/x509_crt_h_115_5)" is not a valid Ident', /home/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.24/src/fallback.rs:693:9
```
If I remember correctly, this is caused by a combination of bindgen/clang-11. Updating the compiler to clang-12 should resolve the issue. Switching to GitHub Actions as part of this PR is a bit weird.

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
> CI failed with:
> 
> ```
>   thread 'main' panicked at '"x509_san_other_name_union_(unnamed_at_vendor/include/mbedtls/x509_crt_h_115_5)" is not a valid Ident', /home/travis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.24/src/fallback.rs:693:9
> ```
> 
> If I remember correctly, this is caused by a combination of bindgen/clang-11. Updating the compiler to clang-12 should resolve the issue. Switching to GitHub Actions as part of this PR is a bit weird.

Actually it's odd because there is actually no change on bindgen crate and clang11. What is only changed is rust toolchain.

**Comment by Taowyoo** [comment]
bors cancel

**Comment by Taowyoo** [comment]
bors try-

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors try

**Review by xinyufort — APPROVED** [review]
As per Slack discussion in thread https://fortanix.slack.com/archives/CK39ZV0KA/p1693421657593469

**Comment by Taowyoo** [comment]
bor r=[xinyufort]

**Pull request merged**
