### PR TITLE
Remove bounds on establish, test that Send gets derived as needed

### PR DESCRIPTION
**Pull request by AdrianCX**

### CODE REVIEW

**Review by jethrogb — COMMENTED** [review]
Please modify the Hyper tests to remove 'static where possible

**Comment by MabezDev** [comment]
Looks good so far. Can the `'static` bound be removed on the following impl? https://github.com/fortanix/rust-mbedtls/blob/51ad965a697e772a3c71b6260a8b20161b9bd907/mbedtls/src/ssl/context.rs#L40

**Comment by AdrianCX** [comment]
> Please modify the Hyper tests to remove 'static where possible

fixed

**Comment by AdrianCX** [comment]
bors retry

**Pull request merged**
