### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dvdplm**
Built on top of https://github.com/fortanix/rust-mbedtls/pull/72 and includes updated dependencies.

### CODE REVIEW

**Comment by boschetto** [comment]
Resolves #5

**Comment by bsdinis** [comment]
Hi, has this PR gone stale? If so, why?

I tested it on my machine and it worked (famous last words, I know, but it seems to be a common occurrence).

Are there changes needed?

**Comment by dvdplm** [comment]
@bsdinis most likely yes, I believe this PR and several others are trying to do the same thing. :(

**Comment by Taowyoo** [comment]
Close this PR since long time no update.
Deps update will be soon done with part of release of using `mbedtls` 3.X

**Pull request closed without merging**
