### PR TITLE
Only require chrono when we actually use it

### PR DESCRIPTION
**Pull request by jack-fortanix**
See #62

### CODE REVIEW

**Comment by Goirad** [comment]
@jack-fortanix This looks good, definitely an oversight on my part. It looks like we just need to update syntex-syntax since NLL error suppression has finally been disabled

**Comment by Goirad** [comment]
On second look though it seems that we would have to update bindgen to update syntex-syntax, so this became a lot more complicated

**Comment by jack-fortanix** [comment]
Yeah I was just looking at that. I think the thing to do is for now is pin the SGX build to use nightly-2019-07-11

**Comment by Goirad** [comment]
Don't we use bindgen for all targets?

**Comment by jack-fortanix** [comment]
Yes, but the problem with syntex-syntax is only on very recent nightly. On stable/beta/older nightly, it warns.

This certainly puts a fire under #5 since this means in a few months we won't have a working build on stable anymore. But pinning the nightly build back a ways (and specifically to what we are using in roche) lets things carry on for now. And re SGX support, we really care about that one snapshot vs whatever nightly happens to be doing this week, so I think it makes more sense to pin in any case.

**Comment by Goirad** [comment]
Oh ok I understand, that makes sense

**Pull request merged**
