### PR TITLE
Add missing error codes

### PR DESCRIPTION
**Pull request by jack-fortanix**

### CODE REVIEW

**Comment by jethrogb** [comment]
I'm confused, I thought I had fixed this macro so that rustfmt would pick it up, but it looks like it somehow didn't?

**Comment by jethrogb** [comment]
Can you please nudge the macro/rustfmt a little bit so it gets this enum?

**Comment by jack-fortanix** [comment]
My fault, forgot to `rustfmt` after rebasing

**Comment by jethrogb** [comment]
Great, I'm still confused why it's not formatted on the left of the diff, but whatever.

bors r+

**Pull request merged**
