### PR TITLE
[v0.7] Move `selftest, threading, time` code to crate `mbedtls-platform-support`

### PR DESCRIPTION
**Pull request by Taowyoo**
1. This PR back-port changes in

	  - https://github.com/fortanix/rust-mbedtls/pull/254
	
    into `v0.7` branch

2. Bump `rust-mbedtls` version to `0.7.4`

The patch in root `Cargo.toml` file will be removed once https://github.com/fortanix/rust-mbedtls/pull/254 is merged and new crates have been published to crates.io

### CODE REVIEW

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors try

**Comment by Taowyoo** [comment]
bors cancel

**Comment by Taowyoo** [comment]
bors try

**Review by arai-fortanix — APPROVED** [review]

**Pull request merged**
